[package]
name = "hypercore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at 
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
log = "0.4"
rsa = "0.5"
rand = "0.8.5"
uuid = "0.8.2"
sha2 = "0.10.2"
serde_json = "1.0.59"